services:
  manalyzer:
    build: ./analyzer
    container_name: analyzer
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /www/wwwroot/mahakala.trade/analyzer/config.yaml:/app/config.yaml
    depends_on:
      - mserver
  mserver:
    build: ./server
    container_name: server
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - /www/wwwroot/mahakala.trade/server/config.yaml:/app/config.yaml
      - /www/wwwroot/mahakala.trade/server/log:/app/log
    depends_on:
      - mtimescaledb
  mtimescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    volumes:
      - /www/wwwroot/mahakala.trade/timescaledb/data:/var/lib/postgresql/data
    command:
      - -c
      - max_connections=1000