services:
  analyzer:
    build: ./analyzer
    container_name: analyzer
    restart: unless-stopped
    volumes:
      - /www/wwwroot/mahakala.trade/analyzer/config.yaml:/app/config.yaml
    depends_on:
      - server
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - /www/wwwroot/mahakala.trade/server/config.yaml:/app/config.yaml
      - /www/wwwroot/mahakala.trade/server/log:/app/log
    extra_hosts:
      - "host.docker.internal:host-gateway"